### ISSUE TITLE
APP Crash

### ISSUE THREAD

**Issue by owls0** [cloudwebrtc/flutter-webrtc#205]
> #### Using IDE running is success, but after build apk, running fails !
> ADB log:
> ```
> 03-14 16:01:02.986 +0000   523   523 W sh      : type=1400 audit(0.0:64832): avc: denied { search } for name="default" dev="tmpfs" ino=105 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:storage_file:s0 tclass=dir permissive=0
> 03-14 16:01:03.037 +0000 27128 27128 I org.webrtc.Logging: NativeLibrary: Loading native library: jingle_peerconnection_so
> 03-14 16:01:03.037 +0000 27128 27128 I org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     :
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     :
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     : #
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     : # Fatal error in: ../../../../usr/local/google/home/sakal/code/webrtc-aar-release/src/sdk/android/src/jni/jni_generator_helper.cc, line 28
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     : # last system error: 88
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     : # Check failed: !clazz.is_null()
> 03-14 16:01:03.040 +0000 27128 27128 E rtc     : # org/webrtc/WebRtcClassLoader
> 03-14 16:01:03.042 +0000   435   435 W         : debuggerd: handling request: pid=27128 uid=10246 gid=10246 tid=27128
> 03-14 16:01:04.016 +0000   435   435 W         : debuggerd: resuming target 27128
> 03-14 16:01:04.028 +0000   591   591 I Zygote  : Process 27128 exited due to signal (6)
> 03-14 16:01:04.044 +0000  1373  1425 I SmartisanLaunch: hot launch com.smartisanos.launcher/.Launcher: 27 ms
> 03-14 16:01:07.996 +0000   523   523 W sh      : type=1400 audit(0.0:64833): avc: denied { search } for name="default" dev="tmpfs" ino=105 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:storage_file:s0 tclass=dir permissive=0
> ```

**Comment by cloudwebrtc** [comment]
Compile fails or running fails?

**Comment by owls0** [comment]
> 编译失败还是运行失败？

running fails ！

**Comment by owls0** [comment]
> Compile fails or running fails?

running fails ！

**Comment by MetinSeylan** [comment]
same

**Comment by cloudwebrtc** [comment]
@owls0 @MetinSeylan Please refer to the differences below to modify your android project, this should be an android build setup issue.
https://github.com/cloudwebrtc/flutter-webrtc/commit/4966ab01bf256ce27f9d32b96a4768100e9e664e

**Comment by ac130kz** [comment]
@cloudwebrtc can confirm. The issue dissapeared after the proguard rules were added.

**Comment by blizzy312** [comment]
@cloudwebrtc First of all, I'd like to thank you for this work, it really helps me to make my work easier. But, I have similar issue, whenever I try to run code on some devices, I got fatal error.

> I/org.webrtc.Logging(10625): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(10625): NativeLibrary: Loading library: jingle_peerconnection_so
D/dalvikvm(10625): Trying to load lib /data/app-lib/com.cloudwebrtc.flutterwebrtcdemo-2/libjingle_peerconnection_so.so 0x420f0808
D/dalvikvm(10625): Added shared lib /data/app-lib/com.cloudwebrtc.flutterwebrtcdemo-2/libjingle_peerconnection_so.so 0x420f0808
I/org.webrtc.Logging(10625): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/org.webrtc.Logging(10625): EglBase10Impl: Using OpenGL ES version 2
W/dalvikvm(10625): DexOpt: method is in an interface
I/dalvikvm(10625): Could not find method android.hardware.camera2.CameraDevice.getId, referenced from method com.cloudwebrtc.webrtc.GetUserMediaImpl.hasTorch
W/dalvikvm(10625): VFY: unable to resolve virtual method 1214: Landroid/hardware/camera2/CameraDevice;.getId ()Ljava/lang/String;
W/dalvikvm(10625): VFY:  rejecting opcode 0x6e at 0x0049
W/dalvikvm(10625): VFY:  rejected Lcom/cloudwebrtc/webrtc/GetUserMediaImpl;.hasTorch (Ljava/lang/String;Lio/flutter/plugin/common/MethodChannel$Result;)V
W/dalvikvm(10625): Verifier rejected class Lcom/cloudwebrtc/webrtc/GetUserMediaImpl;
D/AndroidRuntime(10625): Shutting down VM
W/dalvikvm(10625): threadid=1: thread exiting with uncaught exception (group=0x418e9bc0)
E/AndroidRuntime(10625): FATAL EXCEPTION: main
E/AndroidRuntime(10625): Process: com.cloudwebrtc.flutterwebrtcdemo, PID: 10625
E/AndroidRuntime(10625): java.lang.VerifyError: com/cloudwebrtc/webrtc/GetUserMediaImpl
E/AndroidRuntime(10625):        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.<init>(FlutterWebRTCPlugin.java:114)
E/AndroidRuntime(10625):        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.registerWith(FlutterWebRTCPlugin.java:91)
E/AndroidRuntime(10625):        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
E/AndroidRuntime(10625):        at com.cloudwebrtc.flutterwebrtcdemo.MainActivity.onCreate(MainActivity.java:11)
E/AndroidRuntime(10625):        at android.app.Activity.performCreate(Activity.java:5447)
E/AndroidRuntime(10625):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/AndroidRuntime(10625):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
E/AndroidRuntime(10625):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
E/AndroidRuntime(10625):        at android.app.ActivityThread.access$800(ActivityThread.java:166)
E/AndroidRuntime(10625):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
E/AndroidRuntime(10625):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10625):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10625):        at android.app.ActivityThread.main(ActivityThread.java:5590)
E/AndroidRuntime(10625):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10625):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10625):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
E/AndroidRuntime(10625):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
E/AndroidRuntime(10625):        at dalvik.system.NativeStart.main(Native Method)
I/Process (10625): Sending signal. PID: 10625 SIG: 9

It fails to run on my old device, (Samsung J1, with Android 4.4.4), but works properly on Samsung S8 (with Android 9) and Redmi Note 7. Unfortunately, due to Covid-19, I can't go out to check with additional devices. I'm planning to use this plugin in my production app, so solving this issue beforehand is very critical for me. Be safe and thank you.

**Comment by dreampowder** [comment]
I am having the same error on my older android device. (Android 4.4.2 (API 19))

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] Connected device (3 available)


and this is my build.gradle (app)
`android {
    compileSdkVersion 29
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.uzaktanhastatakip"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 31900001
        versionName '3.1.9'
        multiDexEnabled true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


}

flutter {
    source '../..'
}

dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-messaging:20.1.3'
    implementation 'com.google.android.gms:play-services-base:17.2.0'

}

apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin
apply plugin: 'io.fabric'`

`04-09 18:54:14.156 26916-26916/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.uzaktanhastatakip, PID: 26916
    java.lang.VerifyError: com/cloudwebrtc/webrtc/GetUserMediaImpl
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.<init>(FlutterWebRTCPlugin.java:114)
        at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.registerWith(FlutterWebRTCPlugin.java:91)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:53)
        at com.example.dakik_mobile_app.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:5539)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by tomamatics** [comment]
Adding proguard rules works for me. thanks @cloudwebrtc
