### ISSUE TITLE
great job.

### ISSUE THREAD

**Issue by gaoyuqi** [cloudwebrtc/flutter-webrtc#5]
since Flutter is new to us but popular in the near future what you did is actually great job. 很厉害

**Comment by cloudwebrtc** [comment]
Yes, Flutter is a good UI framework in the future. We have plans to port the desktop WebRTC plugin after [flutter-desktop-embedding](https://github.com/google/flutter-desktop-embedding) support for windows/linux/mac, flutter is awesome.

**Comment by gedw99** [comment]
@cloudwebrtc

I am using flutter desktop. It's working on Mac and Linux and windows looks like it will get working soon.

The plumbing architecture is aligned to the way mobile works now.

Anyway it's not too shabby but not production ready yet I feel.

Would be happy to help get webrtc working there.

I have been using golang for flutter plugins. You just have to wrapper the golang with the favoured OS plugin language.
This gets you an OS agnostic plugin.

I mention this because there is a great webrtc golang library that can be used and so it works on all mobiles and desktops as a flutter plugin.

https://github.com/pions/webrtc

**Comment by cloudwebrtc** [comment]
@gedw99 
I think [https://github.com/pions/webrtc](https://github.com/pions/webrtc) is great for developing server side, but not for client.
Because there are a lot of work to do with using gstreamer and golang as clients:
1. The webrtc standard is implemented by google. Many of the transmission protection protocols, such as fec, nack, rate control, and voice processing (NS, AGC, AEC), are very complicated. Using gstreamer as a client, you need to implement all of them by yourself. 
    The client-side protocol adapts to a large number of native layers of Android devices. It is very difficult to achieve the effect of google webrtc client.

2.the client protocol is difficult to upgrade, once google changes the webrtc part of the algorithm, then the golang client needs to be re-adapted.

If you use the google webrtc framework to develop the flutter plugin, you only need to implementation the api to json message interaction and the RGB/YUV video renderer adaptation, when the google webrtc project is upgraded, our flutter-webrtc plugin can be upgraded.

This ensures that we can get a stable client plugin.

**Comment by gedw99** [comment]
Ah I did not know all of that.

So I think we will try your client in flutter talking to our golang server
then.
